CREATE TABLE TB_THIAGO -- CRIA A TABELA TB_THIAGO
(
	ID_PLAYER BIGINT,
	PLAYER VARCHAR(MAX),
	GAME_PLAYER VARCHAR(MAX)
)

INSERT INTO -- INSERE VALORES NA TABELA TB_THIAGO
	TB_THIAGO
	(ID_PLAYER,PLAYER,GAME_PLAYER)
VALUES
	(2,'FOFO','FORT'),
	(3,'GORDO','FORT'),
	(4,'JUBA','FORT'),
	(5,'CORO','LOL'),
	(6,'HERA','MINE'),
	(7,'LEO','FIFA')

SELECT * -- SELECIONA TUDO QUE TEM NA TABELA TB_THIAGO
FROM TB_THIAGO

DELETE FROM TB_THIAGO -- REMOVE TODAS AS LINHAS QUE POSSUI NOME DO PLAYER = 'HERA' OU JOGO DO PLAYER = 'FORT' DA TABELA TB_THIAGO
WHERE	
	PLAYER = 'HERA'
	OR
	GAME_PLAYER = 'FORT'
	

SELECT * FROM TB_THIAGO -- SELECIONA TODAS AS LINHAS DA TABELA

SELECT * FROM TB_THIAGO -- SELECIONA TODAS AS LINHAS QUE POSSUI NOME DO JOGADOR = 'HERA' OU NOME DO JOGO = 'FORT'
WHERE 
	GAME_PLAYER = 'FORT'
	OR
	PLAYER = 'HERA'

UPDATE -- ATUALIZA TODAS AS PESSOAS QUE TEM NOME = 'CORO' OU JOGA 'LOL' PARA 'HERA' QUE JOGA 'COD'
	TB_THIAGO
SET
	PLAYER = 'HERA',
	GAME_PLAYER = 'COD'
WHERE
	PLAYER = 'CORO'
	OR 
	GAME_PLAYER = 'LOL'

UPDATE -- ATUALIZA TODOS OS NOMES DE PLAYERS QUE TEM ID = 5 PARA LETRA MINUSCULA
	TB_THIAGO
SET 
	PLAYER = LOWER(PLAYER)
WHERE 
	ID_PLAYER = 5

